# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\x12\x0c\x61uth_service\"\x07\n\x05\x45mpty\"\"\n\x0f\x42ooleanResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x83\x01\n\x08UserBlob\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\tuser_type\x18\x04 \x01(\t\x12\x11\n\tentity_id\x18\x05 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x10\n\x08platform\x18\x07 \x01(\t\"I\n\tAuthToken\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x0f\n\x07\x65xpires\x18\x03 \x01(\x03\"\x92\x01\n\x08Userdata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\tuser_type\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x0e\n\x06mobile\x18\x06 \x01(\t\x12\x0f\n\x07\x63reated\x18\x07 \x01(\x03\x12\x10\n\x08username\x18\x08 \x01(\t\"a\n\x11UserLoginResponse\x12&\n\x05token\x18\x01 \x01(\x0b\x32\x17.auth_service.AuthToken\x12$\n\x04user\x18\x02 \x01(\x0b\x32\x16.auth_service.Userdata\"8\n\x15UserLoginWithPassword\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xcc\x01\n\x11RegisterUserInput\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\tuser_type\x18\x04 \x01(\t\x12\x0e\n\x06mobile\x18\x05 \x01(\t\x12\x10\n\x08username\x18\x06 \x01(\t\x12\x10\n\x08password\x18\x07 \x01(\t\x12\x13\n\x0bre_password\x18\x08 \x01(\t\x12\x15\n\rdate_of_birth\x18\t \x01(\t\x12\x0e\n\x06gender\x18\n \x01(\t2\xb2\x01\n\x0b\x41uthService\x12P\n\x0cRegisterUser\x12\x1f.auth_service.RegisterUserInput\x1a\x1f.auth_service.UserLoginResponse\x12Q\n\tLoginUser\x12#.auth_service.UserLoginWithPassword\x1a\x1f.auth_service.UserLoginResponseb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_BOOLEANRESPONSE = DESCRIPTOR.message_types_by_name['BooleanResponse']
_USERBLOB = DESCRIPTOR.message_types_by_name['UserBlob']
_AUTHTOKEN = DESCRIPTOR.message_types_by_name['AuthToken']
_USERDATA = DESCRIPTOR.message_types_by_name['Userdata']
_USERLOGINRESPONSE = DESCRIPTOR.message_types_by_name['UserLoginResponse']
_USERLOGINWITHPASSWORD = DESCRIPTOR.message_types_by_name['UserLoginWithPassword']
_REGISTERUSERINPUT = DESCRIPTOR.message_types_by_name['RegisterUserInput']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.Empty)
  })
_sym_db.RegisterMessage(Empty)

BooleanResponse = _reflection.GeneratedProtocolMessageType('BooleanResponse', (_message.Message,), {
  'DESCRIPTOR' : _BOOLEANRESPONSE,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.BooleanResponse)
  })
_sym_db.RegisterMessage(BooleanResponse)

UserBlob = _reflection.GeneratedProtocolMessageType('UserBlob', (_message.Message,), {
  'DESCRIPTOR' : _USERBLOB,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.UserBlob)
  })
_sym_db.RegisterMessage(UserBlob)

AuthToken = _reflection.GeneratedProtocolMessageType('AuthToken', (_message.Message,), {
  'DESCRIPTOR' : _AUTHTOKEN,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.AuthToken)
  })
_sym_db.RegisterMessage(AuthToken)

Userdata = _reflection.GeneratedProtocolMessageType('Userdata', (_message.Message,), {
  'DESCRIPTOR' : _USERDATA,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.Userdata)
  })
_sym_db.RegisterMessage(Userdata)

UserLoginResponse = _reflection.GeneratedProtocolMessageType('UserLoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERLOGINRESPONSE,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.UserLoginResponse)
  })
_sym_db.RegisterMessage(UserLoginResponse)

UserLoginWithPassword = _reflection.GeneratedProtocolMessageType('UserLoginWithPassword', (_message.Message,), {
  'DESCRIPTOR' : _USERLOGINWITHPASSWORD,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.UserLoginWithPassword)
  })
_sym_db.RegisterMessage(UserLoginWithPassword)

RegisterUserInput = _reflection.GeneratedProtocolMessageType('RegisterUserInput', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERUSERINPUT,
  '__module__' : 'auth_service_pb2'
  # @@protoc_insertion_point(class_scope:auth_service.RegisterUserInput)
  })
_sym_db.RegisterMessage(RegisterUserInput)

_AUTHSERVICE = DESCRIPTOR.services_by_name['AuthService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=36
  _EMPTY._serialized_end=43
  _BOOLEANRESPONSE._serialized_start=45
  _BOOLEANRESPONSE._serialized_end=79
  _USERBLOB._serialized_start=82
  _USERBLOB._serialized_end=213
  _AUTHTOKEN._serialized_start=215
  _AUTHTOKEN._serialized_end=288
  _USERDATA._serialized_start=291
  _USERDATA._serialized_end=437
  _USERLOGINRESPONSE._serialized_start=439
  _USERLOGINRESPONSE._serialized_end=536
  _USERLOGINWITHPASSWORD._serialized_start=538
  _USERLOGINWITHPASSWORD._serialized_end=594
  _REGISTERUSERINPUT._serialized_start=597
  _REGISTERUSERINPUT._serialized_end=801
  _AUTHSERVICE._serialized_start=804
  _AUTHSERVICE._serialized_end=982
# @@protoc_insertion_point(module_scope)
