# Generated by Django 4.0.3 on 2022-03-10 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_mobileotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjwttoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jwt', to=settings.AUTH_USER_MODEL),
        ),
    ]
