# Generated by Django 4.0.3 on 2022-05-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_userjwttoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
